/******************************************************************************
* Author: Vladimir Bessonov
* Date: Sep 23, 2020
* Descpription: Test Class for UpdateDateOnStatusChange

*/

@isTest(SeeAllData=true)
public with sharing class UpdateDateOnStatusChangeTest {
@isTest
static void updateDateSent() {

    // Create Component
    // Update status of part
    // check if date of part is changed

    // on update of component status also check if dates are updated

}
}
