/******************************************************************************
* Author: Vladimir Bessonov
* Date: Aug 30, 2020
* Descpription: Create Object for Project Template. 

*/
// for Propulsion and for Bogie the same template;
public class CreateObjectData {

    public string Name;
    public string APIname;    
    public List<String> PartNameList;
    public List<String> PartMaterialNumberList;
    public List<String> PartSupplierList;
    public List<String> PartSupplierPartNumberList;

}
